apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krmarket-frontend-ingress
  namespace: krmarket
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/x-forwarded-proto: "https"

    # âœ… REQUIRED for SPA on MicroK8s
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: public
  rules:
  - host: krmarket.bezawada.link
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: krmarket-frontend
            port:
              number: 80
