apiVersion: v1
kind: Service
metadata:
  name: ecommerce-client
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
