apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-server
  namespace: ecommerce
  labels:
    app: ecommerce-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-server
  template:
    metadata:
      labels:
        app: ecommerce-server
    spec:
      containers:
        - name: server
          image: ashwinsai22/ecommerce-server:latest
          ports:
            - containerPort: 5000
